package web

import "embed"

// wasm/raster.wasm and wasm/wasm_exec.js are generated by
// scripts/build-wasm.sh (or .ps1) and gitignored — they must exist on disk
// before `go build`/`go vet`/`go test` runs on this module, since go:embed
// reads them at compile time. build.sh/build.bat/scripts/build.ps1 and CI run
// that script automatically; a bare `go build ./cmd/mudp` on a clean
// checkout does not and needs it run once first.
//
//go:embed index.html share.html share.js app.js styles.css world.geojson vendor modules lib wasm
var Files embed.FS
